#ifdef RHI_SWITCHBOARD_ENABLED
#include <Renderer/Renderer.h>

#undef RHI_SWITCHBOARD_ENABLED

#undef RHI_FN_VK_BRANCH
#undef RHI_FN_VK_BRANCH_FALLBACK
#undef RHI_FN_DX12_BRANCH
#undef RHI_FN_DX12_BRANCH_FALLBACK
#undef RHI_FN_MTL_BRANCH
#undef RHI_FN_MTL_BRANCH_FALLBACK
#undef RHI_FN_SWITCH

#endif
