// =============================================================================================================================
// Warnings
#ifndef BRAHMA_NO_WARNINGS

#ifdef _MSC_VER
    #pragma warning(disable: 4100) // unreferenced formal parameter
    #pragma warning(disable: 5045) // spectre mitigation
    #pragma warning(disable: 4324) // structure was padded due to alignment specifier
    #pragma warning(disable: 4820) // bytes padding added after data member
    #pragma warning(disable: 4127) // conditional expression is constant
    #pragma warning(disable: 4514) // unreferenced inline function has been removed
    #pragma warning(disable: 4710) // function not inlined
    #pragma warning(disable: 4711) // function selected for automatic inline expansion
    #pragma warning(disable: 4464) // relative include path contains '..'
    #pragma warning(disable: 5038) // data member will be initialized after base class
    #pragma warning(disable: 4577) // 'noexcept' used with no exception handling mode specified

    #define BRAHMA_SUPPRESS_WARN \
        __pragma(warning(push, 0))

    #define BRAHMA_UNSUPPRESS_WARN \
        __pragma(warning(pop))
#endif

#ifdef __GNUC__
    #pragma GCC diagnostic error   "-Wall"
    #pragma GCC diagnostic error   "-Wextra"
    #pragma GCC diagnostic error   "-Wshadow"
    #pragma GCC diagnostic error   "-Wconversion"
    #pragma GCC diagnostic error   "-Wsign-conversion"
    #pragma GCC diagnostic error   "-Wdouble-promotion"
    #pragma GCC diagnostic error   "-Wfloat-equal"
    #pragma GCC diagnostic error   "-Wundef"
    #pragma GCC diagnostic error   "-Wswitch-enum"
    #pragma GCC diagnostic error   "-Wstrict-prototypes"
    #pragma GCC diagnostic ignored "-Wunused-parameter"

    #define BRAHMA_SUPPRESS_WARN \
        _Pragma("GCC diagnostic push")  \
        _Pragma("GCC diagnostic ignored \"-Weverything\"")

    #define BRAHMA_UNSUPPRESS_WARN \
        _Pragma("GCC diagnostic pop")
#endif

#ifdef __clang__
    #pragma clang diagnostic error   "-Wall"
    #pragma clang diagnostic error   "-Wextra"
    #pragma clang diagnostic error   "-Wshadow"
    #pragma clang diagnostic error   "-Wconversion"
    #pragma clang diagnostic error   "-Wsign-conversion"
    #pragma clang diagnostic error   "-Wdouble-promotion"
    #pragma clang diagnostic error   "-Wfloat-equal"
    #pragma clang diagnostic error   "-Wundef"
    #pragma clang diagnostic error   "-Wswitch-enum"
    #pragma clang diagnostic error   "-Wstrict-prototypes"
    #pragma clang diagnostic ignored "-Wunused-parameter"

    #define BRAHMA_SUPPRESS_WARN \
        _Pragma("clang diagnostic push")  \
        _Pragma("clang diagnostic ignored \"-Weverything\"")

    #define BRAHMA_UNSUPPRESS_WARN \
        _Pragma("clang diagnostic pop")
#endif

#endif//BRAHMA_NO_WARNINGS

// =============================================================================================================================
// Includes
#if 1

#ifdef _WIN32
    #define WIN32_LEAN_AND_MEAN
    #define VC_EXTRALEAN
    #define NOMINMAX
#endif

#ifdef __linux__
    #define _GNU_SOURCE
    #define _POSIX_C_SOURCE 200809L
    #define _XOPEN_SOURCE 700
#endif

#ifdef __APPLE__
    #define _DARWIN_C_SOURCE
#endif

BRAHMA_SUPPRESS_WARN
#include <stdio.h>
#include <stdint.h>
#include <string.h>
BRAHMA_UNSUPPRESS_WARN

#endif

// =============================================================================================================================
// Main header file.
#ifndef BRAHMA_LIBRARY_H
#define BRAHMA_LIBRARY_H

/**
 * Package definition.
 *
 * A package is a single output that is generated by one or more libraries. It could be an executable, a dynamic library,
 * or a static library.
 *
 * An executable package can also optionally depend on other dynamic library packages.
 *
 * A package must declare at least one library that it is dependent on. All the source files in that library (and its dependencies)
 * will be compiled to build the package. The output will also be linked against the static libraries that that library (and its
 * dependencies) might contain.
 */
typedef struct
{
    void* _;
} Brahma_Package;

/**
 * Library definition.
 *
 * A library is a single unit of code that contains one or more input files to build different packages. It could be code files,
 * or a static library.
 *
 * Libraries can also declare dependencies on other libraries. In this case, they will be able to `#include` the headers of the
 * libraries that they are dependent on.
 */
typedef struct
{
    void* _;
} Brahma_Library;

/**
 * Implement a package.
 *
 * Usage:
 * ```
 * BRAHMA_IMPLEMENT_PACKAGE(packageName)
 * {
 *     return (Brahma_Package)
 *     {
 *         // package data...
 *     };
 * }
 * ```
 */
#define BRAHMA_IMPLEMENT_PACKAGE(packageName) \
    Brahma_Package brahma_implement_package_##packageName(void)

/**
 * Implement a library.
 *
 * Usage:
 * ```
 * BRAHMA_IMPLEMENT_LIBRARY(libraryName)
 * {
 *     return (Brahma_Library)
 *     {
 *         // library data...
 *     };
 * }
 * ```
 */
#define BRAHMA_IMPLEMENT_LIBRARY(libraryName) \
    Brahma_Library brahma_implement_library_##libraryName(const Brahma_Package* package)

BRAHMA_IMPLEMENT_LIBRARY(Brahma)
{
    return (Brahma_Library) {0};
}

// =============================================================================================================================
// Execution code (used when CLI is executed).
#ifdef  BRAHMA_EXEC

typedef enum
{
    BRAHMA_INPUT_ARG_FLAGS_NONE      =      0,
    BRAHMA_INPUT_ARG_FLAGS_DEBUG     = 1 << 0,
    BRAHMA_INPUT_ARG_FLAGS_OPTIMISED = 1 << 1,
} Brahma_Input_Args_Flags_Bits;

typedef uint64_t Brahma_Input_Args_Flags;

typedef struct
{
    Brahma_Input_Args_Flags flags;
    char*                   packageToBuild;
} Brahma_Input_Args;

#if !defined(BRAHMA_PACKAGE_COUNT)
#error "Package count not defined. Brahma build tool has not been built correctly."
#define BRAHMA_PACKAGE_COUNT 1
#elif !BRAHMA_PACKAGE_COUNT
#error "No packages defined."
#undef BRAHMA_PACKAGE_COUNT
#define BRAHMA_PACKAGE_COUNT 1
#endif

#if !defined(BRAHMA_LIBRARY_COUNT)
#error "Library count not defined. Brahma build tool has not been built correctly."
#define BRAHMA_LIBRARY_COUNT 1
#elif !BRAHMA_LIBRARY_COUNT
#error "No libraries defined."
#undef BRAHMA_LIBRARY_COUNT
#define BRAHMA_LIBRARY_COUNT 1
#endif

typedef struct
{
    char*          names      [BRAHMA_PACKAGE_COUNT];
    char*          owningFiles[BRAHMA_PACKAGE_COUNT];
    Brahma_Package info       [BRAHMA_PACKAGE_COUNT];
} Brahma_Packages;

typedef struct
{
    char*          names      [BRAHMA_LIBRARY_COUNT];
    char*          owningFiles[BRAHMA_LIBRARY_COUNT];
    Brahma_Library info       [BRAHMA_LIBRARY_COUNT];
} Brahma_Libraries;

// global variable that holds all the package definitions
Brahma_Packages g_BrahmaPkgDefs;

// implemented by the generated code via helper macro
void brahma_create_all_packages(void);

// implemented by the generated code via helper macro
void brahma_create_all_libraries(const Brahma_Package* package);

// add a package, used by the generated code via helper macro
void brahma_add_package(int idx, char* name, char* owningFile, Brahma_Package package);

// add a library, used by the generated code via helper macro
void brahma_add_library(int idx, char* name, char* owningFile, Brahma_Library library);

int main(int argc, char* argv[])
{
    Brahma_Input_Args inputArgs = {0};
    inputArgs.flags |= BRAHMA_INPUT_ARG_FLAGS_DEBUG; // default to debug mode

    for (int i = 1; i < argc; i++) // skipping first arg because it's gonna be the executable name
    {
        // intermediate stuff - not relevant once this tool has begun executing
        if (!strcmp("-modules_search_dir", argv[i])) { i++; continue; } // module search dirs
        if (!strcmp("-build_tool_path",    argv[i])) { i++; continue; } // the path where the build tool was compiled

        // flags
        if (!strcmp("-nodebuginfo", argv[i])) { inputArgs.flags &= ~BRAHMA_INPUT_ARG_FLAGS_DEBUG;     continue; }
        if (!strcmp("-optimised",   argv[i])) { inputArgs.flags |=  BRAHMA_INPUT_ARG_FLAGS_OPTIMISED; continue; }

        if (!strcmp("-package", argv[i]))
        {
            if (inputArgs.packageToBuild)
            {
                printf("ERROR: Multiple packages specified with -package. Use as: *.exe -package packageName. Press any key to exit...");
                getchar();
                return 1;
            }

            if (++i >= argc)
            {
                printf("ERROR: No package specified after -package. Use as: *.exe -package packageName. Press any key to exit...");
                getchar();
                return 1;
            }

            inputArgs.packageToBuild = argv[i];
        }
    }

    brahma_create_all_packages();

    // find the package to build
    int selectedPkgIdx = -1;
    {
        if (!inputArgs.packageToBuild)
        {
            printf("No package specified. Defaulting to the first package!\n");
            selectedPkgIdx = 0;
        }
        else
        {
            for (int i = 0; i < BRAHMA_PACKAGE_COUNT; i++)
            {
                if (!strcmp(inputArgs.packageToBuild, g_BrahmaPkgDefs.names[i]))
                {
                    selectedPkgIdx = i;
                    break;
                }
            }

            if (selectedPkgIdx == -1)
            {
                printf("ERROR: No package found with the name '%s'. Press any key to exit...", inputArgs.packageToBuild);
                getchar();
                return 1;
            }
        }
    }

    printf("-----------------------------------------\n");
    printf("Brahma Configuration:\n");
    printf("\tSelected package: %s.\n", g_BrahmaPkgDefs.names[selectedPkgIdx]);
    printf("\tDebug info:       %s.\n", (inputArgs.flags & BRAHMA_INPUT_ARG_FLAGS_DEBUG)     ? "on" : "off");
    printf("\tOptimised:        %s.\n", (inputArgs.flags & BRAHMA_INPUT_ARG_FLAGS_OPTIMISED) ? "on" : "off");
    printf("-----------------------------------------\n");

    return 0;
}

#define BRAHMA_BEGIN_LISTING_PACKAGES() \
    void brahma_create_all_packages(void) {

#define BRAHMA_END_LISTING_PACKAGES() \
    }

#define BRAHMA_BEGIN_LISTING_LIBRARIES() \
    void brahma_create_all_libraries(const Brahma_Package* package) {

#define BRAHMA_END_LISTING_LIBRARIES() \
    }

#define BRAHMA_ADD_PACKAGE(idx, path, packageName) \
    brahma_add_package(idx, #packageName, path, brahma_implement_package_##packageName());

#define BRAHMA_ADD_LIBRARY(idx, path, libraryName) \
    brahma_add_library(idx, #libraryName, path, brahma_implement_library_##libraryName(package));

void brahma_add_package(int idx, char* name, char* owningFile, Brahma_Package package)
{
    g_BrahmaPkgDefs.names[idx]       = name;
    g_BrahmaPkgDefs.owningFiles[idx] = owningFile;
    g_BrahmaPkgDefs.info[idx]        = package;
}

void brahma_add_library(int idx, char* name, char* owningFile, Brahma_Library library)
{
    // TOOD
}

#endif//BRAHMA_EXEC

#endif//BRAHMA_LIBRARY_H
