// =============================================================================================================================
// Warnings
#ifndef BRAHMA_NO_WARNINGS

#ifdef _MSC_VER
    #pragma warning(disable: 4100) // unreferenced formal parameter
    #pragma warning(disable: 5045) // spectre mitigation
    #pragma warning(disable: 4324) // structure was padded due to alignment specifier
    #pragma warning(disable: 4820) // bytes padding added after data member
    #pragma warning(disable: 4127) // conditional expression is constant
    #pragma warning(disable: 4514) // unreferenced inline function has been removed
    #pragma warning(disable: 4710) // function not inlined
    #pragma warning(disable: 4711) // function selected for automatic inline expansion
    #pragma warning(disable: 4464) // relative include path contains '..'
    #pragma warning(disable: 5038) // data member will be initialized after base class
    #pragma warning(disable: 4577) // 'noexcept' used with no exception handling mode specified

    #define BRAHMA_SUPPRESS_WARN \
        __pragma(warning(push, 0))

    #define BRAHMA_UNSUPPRESS_WARN \
        __pragma(warning(pop))
#endif

#ifdef __GNUC__
    #pragma GCC diagnostic error   "-Wall"
    #pragma GCC diagnostic error   "-Wextra"
    #pragma GCC diagnostic error   "-Wshadow"
    #pragma GCC diagnostic error   "-Wconversion"
    #pragma GCC diagnostic error   "-Wsign-conversion"
    #pragma GCC diagnostic error   "-Wdouble-promotion"
    #pragma GCC diagnostic error   "-Wfloat-equal"
    #pragma GCC diagnostic error   "-Wundef"
    #pragma GCC diagnostic error   "-Wswitch-enum"
    #pragma GCC diagnostic error   "-Wstrict-prototypes"
    #pragma GCC diagnostic ignored "-Wunused-parameter"

    #define BRAHMA_SUPPRESS_WARN \
        _Pragma("GCC diagnostic push")  \
        _Pragma("GCC diagnostic ignored \"-Weverything\"")

    #define BRAHMA_UNSUPPRESS_WARN \
        _Pragma("GCC diagnostic pop")
#endif

#ifdef __clang__
    #pragma clang diagnostic error   "-Wall"
    #pragma clang diagnostic error   "-Wextra"
    #pragma clang diagnostic error   "-Wshadow"
    #pragma clang diagnostic error   "-Wconversion"
    #pragma clang diagnostic error   "-Wsign-conversion"
    #pragma clang diagnostic error   "-Wdouble-promotion"
    #pragma clang diagnostic error   "-Wfloat-equal"
    #pragma clang diagnostic error   "-Wundef"
    #pragma clang diagnostic error   "-Wswitch-enum"
    #pragma clang diagnostic error   "-Wstrict-prototypes"
    #pragma clang diagnostic ignored "-Wunused-parameter"

    #define BRAHMA_SUPPRESS_WARN \
        _Pragma("clang diagnostic push")  \
        _Pragma("clang diagnostic ignored \"-Weverything\"")

    #define BRAHMA_UNSUPPRESS_WARN \
        _Pragma("clang diagnostic pop")
#endif

#endif//BRAHMA_NO_WARNINGS

// =============================================================================================================================
// Includes
BRAHMA_SUPPRESS_WARN
#include <stdio.h>
#include <stdint.h>
BRAHMA_UNSUPPRESS_WARN

// =============================================================================================================================
// Main header file.
#ifndef BRAHMA_LIBRARY_H
#define BRAHMA_LIBRARY_H

/**
 * Package definition.
 *
 * A package is a single output that is generated by one or more libraries. It could be an executable, a dynamic library,
 * or a static library.
 *
 * An executable package can also optionally depend on other dynamic library packages.
 *
 * A package must declare at least one library that it is dependent on. All the source files in that library (and its dependencies)
 * will be compiled to build the package. The output will also be linked against the static libraries that that library (and its
 * dependencies) might contain.
 */
typedef struct Brahma_Package
{
    void* _;
} Brahma_Package;

/**
 * Library definition.
 *
 * A library is a single unit of code that contains one or more input files to build different packages. It could be code files,
 * or a static library.
 *
 * Libraries can also declare dependencies on other libraries. In this case, they will be able to `#include` the headers of the
 * libraries that they are dependent on.
 */
typedef struct Brahma_Library
{
    void* _;
} Brahma_Library;

/**
 * Implement a package.
 *
 * Usage:
 * ```
 * BRAHMA_IMPLEMENT_PACKAGE(packageName)
 * {
 *     return (Brahma_Package)
 *     {
 *         // package data...
 *     };
 * }
 * ```
 */
#define BRAHMA_IMPLEMENT_PACKAGE(packageName) \
    Brahma_Package brahma_implement_package_##packageName(void)

/**
 * Implement a library.
 *
 * Usage:
 * ```
 * BRAHMA_IMPLEMENT_LIBRARY(libraryName)
 * {
 *     return (Brahma_Library)
 *     {
 *         // library data...
 *     };
 * }
 * ```
 */
#define BRAHMA_IMPLEMENT_LIBRARY(libraryName) \
    Brahma_Library brahma_implement_library_##libraryName(const Brahma_Package* package)

BRAHMA_IMPLEMENT_LIBRARY(brahma)
{
    return (Brahma_Library) {0};
}

// =============================================================================================================================
// Execution code (used when CLI is executed).
#ifdef  BRAHMA_EXEC

void brahma_add_package(char* name, char* owningFile, Brahma_Package package) { /* TODO */ }
void brahma_add_library(char* name, char* owningFile, Brahma_Library library) { /* TODO */ }

int main(int argc, char* argv[])
{
    printf("Hello, world!");
    return 0;
}

#define BRAHMA_BEGIN_LISTING_PACKAGES()        void brahma_create_all_packages(void) {
#define BRAHMA_ADD_PACKAGE(path, packageName)      brahma_add_package(#packageName, path, brahma_implement_package_##packageName());
#define BRAHMA_END_LISTING_PACKAGES()          }

#define BRAHMA_BEGIN_LISTING_LIBRARIES()       void brahma_create_all_libraries(const Brahma_Package* package) {
#define BRAHMA_ADD_LIBRARY(path, libraryName)      brahma_add_library(#libraryName, path, brahma_implement_library_##libraryName(package));
#define BRAHMA_END_LISTING_LIBRARIES()         }

#endif//BRAHMA_EXEC

#endif//BRAHMA_LIBRARY_H
